### ISSUE TITLE
Rendering sub-templates?

### ISSUE THREAD

**Issue by khromov** [slimphp/PHP-View#34]
How would you render sub-templates when working with PHP-View? For example, this simple code is not working ("Content" gets outputted last, after the header/footer templates)

```
$app->get('/', function (Request $request, Response $response) {
    return $this->renderer->render($response, "/pages/main.php");
});

//In main.php
<?php $this->render($response, "/header.php", []); ?>
Content
<?php $this->render($response, "/footer.php", []); ?>
```

I do understand why it's not working (Only one response object), but not how to fix it in a proper way?

**Comment by khromov** [comment]
Found a way to get the intended effect: 

```
<?php echo $this->fetch("/header.php", []); ?>
Content
<?php echo $this->fetch("/footer.php", []); ?>
```

Self-closing this.

**Comment by Erutan409** [comment]
I think I figured out why:

https://stackoverflow.com/a/5946766/3257871

Using the `::render()` method from the view container, I was creating a new response to holding the rendered stream in.  Since, each instance will essentially create a new temp file stream, it was flushing the content of a partial I was including before the rest of its parent could be rendered, first.
